# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  simulatorLambdaFunctions

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  getThingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ./get-things/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: fetch things from AWS IOT.
      Environment:
        Variables:
          AWS_RESOURCE_REGION: ""
  d2cSimulatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: d2c-simulator/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: publish data to AWS IoT core.
      Environment:
        Variables:
          AWS_IOT_CONNECTION_ENDPOINT: ""
          AWS_MQTT_TOPIC: ""
          AWS_RESOURCE_REGION: ""
  updateThingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: update-Thing/index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Description: update thing in AWS IoT core.
      Environment:
        Variables:
          AWS_RESOURCE_REGION: ""
      
    